#Requires -Version 5.1
<#
.SYNOPSIS
업비트 시그널 D+7 종합 회고 자동 생성 (운영 가이드 §7)

.DESCRIPTION
state\daily_check.jsonl을 읽어 7일 종합 통계 계산 →
v2.0_operation_log.md의 D+7 회고 섹션에 마크다운 표 자동 patch.

.EXAMPLE
.\weekly_summary.ps1
#>

$PROJECT = "C:\Users\user3\Desktop\VibeCoding\signal-up"
$DAILY_LOG = "$PROJECT\state\daily_check.jsonl"
$OPS_LOG = "C:\Users\user3\Documents\Claude\Projects\시그널 프로그램\handoff\v2.0_operation_log.md"

if (-not (Test-Path $DAILY_LOG)) {
    Write-Host "FAIL: $DAILY_LOG 가 없습니다. daily_check.ps1을 매일 돌렸는지 확인하세요." -ForegroundColor Red
    exit 1
}

Write-Host "`n=== Weekly Summary ===" -ForegroundColor Cyan
$entries = Get-Content $DAILY_LOG | ForEach-Object { $_ | ConvertFrom-Json }
Write-Host "총 데일리 엔트리: $($entries.Count) 개"

# 통계 계산
$alive_days = ($entries | Where-Object { $_.daemon_alive }).Count
$total_signals = ($entries | Measure-Object signals_count -Sum).Sum
if (-not $total_signals) { $total_signals = 0 }
$mems = $entries | Where-Object { $_.daemon_memory_mb -ne $null } | Select-Object -ExpandProperty daemon_memory_mb
$mem_avg = if ($mems) { [math]::Round(($mems | Measure-Object -Average).Average, 1) } else { 0 }
$mem_max = if ($mems) { ($mems | Measure-Object -Maximum).Maximum } else { 0 }
$telegram_ok_days = ($entries | Where-Object { $_.telegram_status -eq 200 }).Count
$backups_max = ($entries | Measure-Object backups_total -Maximum).Maximum
if (-not $backups_max) { $backups_max = 0 }

# 마켓 분포 종합 (top_markets 문자열 파싱)
$market_counts = @{}
foreach ($e in $entries) {
    if ($e.signals_top_markets) {
        foreach ($pair in ($e.signals_top_markets -split ", ")) {
            if ($pair -match "^(\S+)x(\d+)$") {
                $m = $Matches[1]
                $c = [int]$Matches[2]
                if ($market_counts.ContainsKey($m)) { $market_counts[$m] += $c } else { $market_counts[$m] = $c }
            }
        }
    }
}
$top_markets = $market_counts.GetEnumerator() | Sort-Object Value -Descending | Select-Object -First 5

# 마크다운 표 작성
$markets_table = if ($top_markets) {
    ($top_markets | ForEach-Object { "| $($_.Key) | $($_.Value) 건 |" }) -join "`n"
} else {
    "| (시그널 없음) | 0 |"
}

$daily_rows = ($entries | ForEach-Object {
    $alive = if ($_.daemon_alive) { "OK" } else { "DOWN" }
    "| $($_.yesterday) | $alive | $($_.daemon_memory_mb) | $($_.signals_count) | $($_.telegram_status) | $($_.backups_total) |"
}) -join "`n"

$summary_md = @"
### 통계 (자동 추출 — $(Get-Date -Format 'yyyy-MM-dd HH:mm'))

| 지표 | 값 |
|---|---|
| 데몬 alive 일수 | $alive_days / $($entries.Count) 일 |
| 총 시그널 | $total_signals 건 |
| 메모리 평균 / 최대 | $mem_avg MB / $mem_max MB |
| 텔레그램 OK 일수 | $telegram_ok_days / $($entries.Count) 일 |
| 백업 누적 (최대) | $backups_max 개 |

### 마켓 분포 Top 5

| 마켓 | 시그널 |
|---|---|
$markets_table

### 일별 데이터

| 어제 날짜 | 데몬 | 메모리 MB | 시그널 | TG | 백업 |
|---|---|---|---|---|---|
$daily_rows
"@

Write-Host "`n--- 생성된 표 ---" -ForegroundColor Yellow
Write-Host $summary_md

# 운영 로그에 자동 patch
if (Test-Path $OPS_LOG) {
    $log_content = Get-Content $OPS_LOG -Raw -Encoding utf8
    $anchor = "## D+7 종합 회고"

    if ($log_content -match [regex]::Escape($anchor)) {
        $auto_block = "`n`n<!-- AUTO-GENERATED by weekly_summary.ps1 at $(Get-Date -Format 'yyyy-MM-dd HH:mm') -->`n$summary_md`n<!-- END AUTO-GENERATED -->"

        if ($log_content -match "<!-- AUTO-GENERATED by weekly_summary.ps1[\s\S]*?<!-- END AUTO-GENERATED -->") {
            $new_content = [regex]::Replace($log_content, "<!-- AUTO-GENERATED by weekly_summary.ps1[\s\S]*?<!-- END AUTO-GENERATED -->", $auto_block.Trim())
            Write-Host "`n기존 AUTO 블록을 교체했습니다." -ForegroundColor Yellow
        } else {
            $new_content = $log_content -replace [regex]::Escape($anchor), "$anchor$auto_block"
            Write-Host "`nAUTO 블록을 D+7 회고 섹션에 삽입했습니다." -ForegroundColor Green
        }
        [System.IO.File]::WriteAllText($OPS_LOG, $new_content, (New-Object System.Text.UTF8Encoding $false))
        Write-Host "[OK] $OPS_LOG 갱신 완료"
    } else {
        Write-Host "[WARN] '$anchor' 앵커를 찾지 못함. 위 표를 수동 복붙하세요." -ForegroundColor Yellow
    }
} else {
    Write-Host "[WARN] $OPS_LOG 없음. 콘솔 출력만 사용하세요." -ForegroundColor Yellow
}

Write-Host "`n=== 완료 ===" -ForegroundColor Cyan
